#!/usr/bin/env bash
set -x
ocamlbuild -use-ocamlfind \
    src/moc_DataItem_c.c src/moc_Controller_c.c src/moc_AbstractModel_c.c src/moc_HistoryModel_c.c
# exit 0

ocamlbuild -use-ocamlfind \
    src/qrc_resources.c

ocamlbuild -use-ocamlfind \
    src/libcppstubs.a \
    src/program.native -verbose 1
